[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
#halt_afterwards = false
restore_unwritten_bytes = false

[default.reset]
enabled = true
#halt_afterwards = false

[default.general]
chip = "STM32F103C8"
# Use this if you have a different STM32F411 variant:
# chip = "STM32F411RETx"  # for 512KB Flash variant
# chip = "STM32F411VETx"  # for 512KB Flash, 100-pin variant

[default.rtt]
enabled = true
#up_mode = "NoBlockSkip"
#up_buffer_size = 1024
up_channels = [
   # { up = 0, down = 0, name = "Terminal", up_mode = "NoBlockSkip", format = "String" },
]

[default.gdb]
enabled = false  # Set to true if you want GDB server
gdb_connection_string = "127.0.0.1:1337"
